<?php

$config['menu'] =  array(
    //'Home'=>array('show'=>true,'text'=>'控制台','icon'=>'icon-dashboard','target'=>'sys-dashboard','children'=>array()),
    'Signout'=>array(
    	'show'=>true,
    	'text'=>'退出',
    	'icon'=>'icon-signout',
    	'target'=>'Auth-logout',
    	'children'=>array()
    ),
    'ChPass'=>array(
    	'show'=>true,
    	'text'=>'修改密码',
    	'icon'=>'icon-shield',
    	'target'=>'Home-chpass',
    	'children'=>array()
    ),
    'Priv'=>array(
    	'show'=>true,
    	'text'=>'平台管理',
    	'icon'=>'icon-user',
    	'target'=>'Priv',
    	'children'=>array(
    		'Role'=>array(
    			'show'=>true,
    			'text'=>'职能管理',
    			'icon'=>'icon-user',
    			'target'=>'Priv-role',
    			'children'=>array()
    		),
    		'User'=>array(
    			'show'=>true,
    			'text'=>'员工管理',
    			'icon'=>'icon-user',
    			'target'=>'Priv-user',
    			'children'=>array()
    		),
    	)
    ),
    'Qiye'=>array(
    	'show'=>true,
    	'text'=>'企业管理',
    	'icon'=>'icon-info',
    	'target'=>'Qiye',
    	'children'=>array(
    		'Reg'=>array(
    			'show'=>true,
    			'text'=>'新增企业',
    			'icon'=>'icon-info',
    			'target'=>'Qiye-reg',
    			'children'=>array()
    		),
    		'Regaudit'=>array(
    			'show'=>true,
    			'text'=>'企业核查',
    			'icon'=>'icon-info',
    			'target'=>'Qiye-regaudit',
    			'children'=>array()
    		),
    		'Audit'=>array(
    			'show'=>true,
    			'text'=>'企业开户审核',
    			'icon'=>'icon-info',
    			'target'=>'Qiye-audit',
    			'children'=>array()
    		),
    		'query'=>array(
    			'show'=>true,
    			'text'=>'企业查询',
    			'icon'=>'icon-info',
    			'target'=>'Qiye-query',
    			'children'=>array()
    		),
    		'prove'=>array(
    			'show'=>true,
    			'text'=>'企业证据池',
    			'icon'=>'icon-info',
    			'target'=>'Qiye-prove',
    			'children'=>array()
    		),
    	)
    ),
    'Qudao'=>array(
    	'show'=>true,
    	'text'=>'渠道管理',
    	'icon'=>'icon-search',
    	'target'=>'Qudao',
    	'children'=>array(
    		'Add'=>array(
    			'show'=>true,
    			'text'=>'新增渠道',
    			'icon'=>'icon-search',
    			'target'=>'Qudao-add',
    			'children'=>array()
    		),
    		'Query'=>array(
    			'show'=>true,
    			'text'=>'渠道查询',
    			'icon'=>'icon-search',
    			'target'=>'Qudao-query',
    			'children'=>array()
    		),
    	)
    ),
    'Sp'=>array(
    	'show'=>true,
    	'text'=>'产品管理',
    	'icon'=>'icon-double-angle-right',
    	'target'=>'Sp',
    	'children'=>array(
    		'Add'=>array(
    			'show'=>true,
    			'text'=>'新增产品',
    			'icon'=>'icon-double-angle-right',
    			'target'=>'Sp-add',
    			'children'=>array()
    		),
    		'Query'=>array(
    			'show'=>true,
    			'text'=>'产品查询',
    			'icon'=>'icon-double-angle-right',
    			'target'=>'Sp-query',
    			'children'=>array()
    		),
    	)
    ),
    'Order'=>array(
    	'show'=>true,
    	'text'=>'订单管理',
    	'icon'=>'icon-home',
    	'target'=>'Order',
    	'children'=>array(
    		'Gen'=>array(
    			'show'=>true,
    			'text'=>'订单录入',
    			'icon'=>'icon-home',
    			'target'=>'Order-gen',
    			'children'=>array()
    		),
    		'Check'=>array(
    			'show'=>true,
    			'text'=>'订单初审',
    			'icon'=>'icon-home',
    			'target'=>'Order-check',
    			'children'=>array()
    		),
    		'Audit'=>array(
    			'show'=>true,
    			'text'=>'订单终审',
    			'icon'=>'icon-home',
    			'target'=>'Order-audit',
    			'children'=>array()
    		),
    		'Query'=>array(
    			'show'=>true,
    			'text'=>'订单查询',
    			'icon'=>'icon-home',
    			'target'=>'Order-query',
    			'children'=>array()
    		),
    	)
    ),
);